apiVersion: batch/v1
kind: Job
metadata:
  name: github-issue-job
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: github-issue
        image: registry.access.redhat.com/ubi8-minimal:8.7-1031
        envFrom:
        - secretRef:
            name: gh-details
        command: ["/bin/bash", "-c"]
        args: ["curl -u $USERNAME:$TOKEN -X POST -d '{\"title\":\"Deployment sync Done\",\"body\":\"The web site not Healthy.\"}' $URL" ]
      restartPolicy: Never
  backoffLimit: 1