kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.containers.containerPort }}
  selector:
    app1: "{{ .Release.Name }}-1"
    app2: "{{ .Release.Name }}-2"