ReplicaNumber: 1
test: Healthy
containers:
  containerPort: 8080
  image: 'quay.io/yuvalti/image-yuval'
  tag: 'chart_v1'
probes:
  readiness:
    path: /health/readiness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    successThreshold: 3
  liveness:
    path: /health/liveness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    successThreshold: 3
  volume:
    mount:
      path: /tmp/html
service:
  servicePort: 8080